name: kutim
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  animations: ^2.0.11
  app_links: ^6.3.3
  auto_route: ^9.2.2
  badges: ^3.1.2
  bloc: ^8.1.4
  bloc_concurrency: ^0.2.5
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  change_app_package_name: ^1.4.0
  clock: ^1.1.1
  collection: ^1.18.0
  cronet_http: ^1.3.2
  cupertino_http: ^1.5.1
  dio: ^5.7.0
  dots_indicator: ^3.0.0
  drift: ^2.20.0
  drift_flutter: ^0.2.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_linkify: ^6.0.0
  # flutter_local_notifications: ^18.0.1
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  flutter_widget_from_html: ^0.15.2
  fluttertoast: ^8.2.8
  freezed_annotation:
  gap: ^3.0.1
  google_fonts: ^6.2.1
  grouped_list: ^5.1.2
  http: ^1.2.2
  image_picker: ^1.1.2
  intercepted_client: ^0.0.1
  intl: ^0.19.0
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  loader_overlay: ^4.0.2+1
  lottie: ^3.1.2
  mask_text_input_formatter: ^2.9.0
  meta: ^1.15.0
  package_info_plus: ^8.0.2
  path: ^1.9.0
  pinput: ^5.0.0
  pull_to_refresh: ^2.0.0
  pure: ^0.3.0
  rxdart: ^0.28.0
  sentry_flutter: ^8.9.0
  share_plus: ^10.1.3
  shared_preferences: ^2.3.2
  shimmer: ^3.0.0
  stack_trace: ^1.11.1
  stream_bloc: ^0.5.3
  talker: ^4.4.1
  talker_bloc_logger: ^4.4.1
  talker_dio_logger: ^4.4.1
  talker_logger: ^4.4.1
  timeago: ^3.7.0
  tuple: ^2.0.2
  url_launcher: ^6.3.1
  webview_flutter: ^4.10.0
  webview_flutter_wkwebview: ^3.17.0
  local_hero_transform: ^0.0.3
  provider: ^6.1.2
  flutter_native_splash: ^2.4.4


dev_dependencies:
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.12
  drift_dev: ^2.20.1
  flutter_gen_runner: ^5.7.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  lint: ^2.3.0
  ws: ^1.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/icons/
    - assets/images/svg/
    - assets/images/png/
    - assets/images/webp/
    - assets/images/

flutter_gen:
  output: lib/src/core/gen
  integrations:
    flutter_svg: true
    rive: true
    lottie: true

